export type {
  TrendDirection,
  TrendPoint,
  TrendSummary,
  DashboardAnalytics,
  FinanceAnalytics,
  AttendanceAnalytics,
  PendingApprovalsSummary,
  EnquiryAnalytics,
  WidgetId,
  WidgetSize,
  WidgetMeta,
  WidgetLayoutItem,
  DashboardLayout,
} from "./dashboard.types";
