// ══════════════════════════════════════════════════════════════════
// AiSensy WhatsApp API  — smart-ark integration
// Docs: https://documenter.getpostman.com/view/21900476/2s9YsGit5Q
//
// ARCHITECTURE
// ─────────────
// Browser → Supabase Edge Function (send-whatsapp) → AiSensy API
//
// The client NEVER calls AiSensy directly because:
//   1. AiSensy API does not allow cross-origin browser requests (CORS)
//   2. The API key must stay server-side (never in the JS bundle)
//
// All WhatsApp sends go through supabase.functions.invoke("send-whatsapp")
// which reads AISENSY_API_KEY from Supabase secrets and calls AiSensy
// server-to-server.
//
// REQUIRED AISENSY CAMPAIGNS  (create once in your AiSensy dashboard)
// All templates must be submitted to Meta under category = UTILITY.
// IMPORTANT: Meta rejects templates that start or end with a {{variable}}
//            — always wrap variables in static text.
// ────────────────────────────────────────────────────────────────────
// 1. Campaign name : ark_student_marks_report   (7 variables)
//    Template body : "Dear Parent,\n\nWe are pleased to share the latest
//                    academic result.\n\nStudent: {{1}}\nSubject: {{2}}\n
//                    Score: {{3}} / {{4}}\nPercentage: {{5}}%\nGrade: {{6}}\n\n
//                    Remarks:\n{{7}}\n\nThank you,\nARK Learning Arena"
//    Variables     : {{1}}=student  {{2}}=subject+exam  {{3}}=marks
//                    {{4}}=total    {{5}}=percentage   {{6}}=grade  {{7}}=remarks
//
// 2. Campaign name : ark_daily_report_summary   (2 variables)
//    Template body : "ARK Daily Report – {{1}}\n\n{{2}}\n\n
//                    – Auto-generated by ARK Learning Arena"
//    Variables     : {{1}}=date  {{2}}=report text (up to 1024 chars)
//
// 3. Campaign name : ark_fee_payment_reminder   (3 variables, optional)
//    Template body : "Dear Parent, {{1}}'s tuition fee of ₹{{2}} is due by
//                    {{3}}. Kindly arrange the payment at the centre or
//                    contact us for assistance."
//    Variables     : {{1}}=student name  {{2}}=amount  {{3}}=due date
// ══════════════════════════════════════════════════════════════════

import { supabase } from "@/integrations/supabase/client";

/** Campaign names — must match exactly what you create in AiSensy dashboard */
export const CAMPAIGNS = {
  MARKS_REPORT:  "ark_student_marks_report",
  DAILY_REPORT:  "ark_daily_report_summary",
  FEE_REMINDER:  "ark_fee_payment_reminder",
  WALK_IN_ALERT: "ark_walk_in_notification",
  // Required AiSensy template for broadcast:
  //   Campaign name : ark_broadcast_alert
  //   Template body : "{{1}}"   (single variable = the full message text)
  BROADCAST:     "ark_broadcast_alert",
} as const;

// ── Phone normaliser ────────────────────────────────────────────────────────

/**
 * Returns phone in +91XXXXXXXXXX format (required by AiSensy).
 * Handles 10-digit bare, 0XXXXXXXXXX, +91XXXXXXXXXX, 91XXXXXXXXXX, etc.
 */
export function normalisePhone(phone: string): string {
  const digits = phone.replace(/[^0-9]/g, "");
  let withCC: string;
  if (digits.length === 10)                               withCC = "91" + digits;
  else if (digits.startsWith("0") && digits.length === 11) withCC = "91" + digits.slice(1);
  else                                                     withCC = digits;
  return withCC.startsWith("+") ? withCC : "+" + withCC;
}

// ── WhatsApp direct-link fallback ───────────────────────────────────────────

/**
 * Returns a wa.me deep-link (bare digits, no +).
 * Returns "" when phone is empty so callers can guard before window.open.
 */
export function getWhatsAppLink(phone: string, message: string): string {
  const digits = phone.replace(/[^0-9]/g, "");
  if (!digits) return "";
  return `https://wa.me/${digits}?text=${encodeURIComponent(message)}`;
}

// ── Result type ────────────────────────────────────────────────────────────

export interface AisensyResult {
  success: boolean;
  message: string;
}

// ── Core send function — routes through the edge function proxy ────────────

interface SendParams {
  campaignName:    string;
  destination:     string;  // will be normalised inside
  recipientName:   string;  // display name in AiSensy CRM
  templateParams?: string[];
  media?:          { url?: string; filename?: string; caption?: string };
}

export async function sendWhatsApp(params: SendParams): Promise<AisensyResult> {
  try {
    const { data, error } = await supabase.functions.invoke("send-whatsapp", {
      body: {
        campaignName:   params.campaignName,
        destination:    normalisePhone(params.destination),
        recipientName:  params.recipientName,
        templateParams: params.templateParams,
        media:          params.media?.url ? params.media : undefined,
      },
    });

    if (error) {
      return {
        success: false,
        message: `Edge function error: ${error.message}`,
      };
    }

    return data as AisensyResult;
  } catch (err: any) {
    return {
      success: false,
      message: `Network error: ${err?.message || "Could not reach send-whatsapp function"}`,
    };
  }
}

// ── High-level helpers ──────────────────────────────────────────────────────

/**
 * Send student marks report to parent via WhatsApp.
 *
 * Required AiSensy template (campaign: ark_student_marks_report) — 8 variables:
 *  Template (7 variables — matches AiSensy campaign):
 *  "Dear Parent,\n\nWe are pleased to share the latest academic result.\n\n
 *   Student: {{1}}\nSubject: {{2}}\nScore: {{3}} / {{4}}\nPercentage: {{5}}%\n
 *   Grade: {{6}}\n\nRemarks:\n{{7}}\n\nARK Learning Arena"
 */
export async function sendMarksToParent(params: {
  parentPhone:  string;
  parentName?:  string;
  studentName:  string;
  marks:        number;
  totalMarks:   number;
  subject:      string;
  examType:     string;
  remarks:      string;
  teacherName?: string;   // kept for backwards compat, not in template
}): Promise<AisensyResult> {
  const pct = Math.round((params.marks / params.totalMarks) * 100);
  let grade = "Excellent";
  if (pct < 40)      grade = "Needs Improvement";
  else if (pct < 60) grade = "Below Average";
  else if (pct < 75) grade = "Average";
  else if (pct < 90) grade = "Good";

  return sendWhatsApp({
    campaignName:   CAMPAIGNS.MARKS_REPORT,
    destination:    params.parentPhone,
    recipientName:  params.parentName || `Parent of ${params.studentName}`,
    templateParams: [
      params.studentName,                         // {{1}} Student
      `${params.subject} (${params.examType})`,   // {{2}} Subject
      String(params.marks),                       // {{3}} Score
      String(params.totalMarks),                  // {{4}} Total
      String(pct),                                // {{5}} Percentage
      grade,                                      // {{6}} Grade
      params.remarks || "No remarks",             // {{7}} Remarks
    ],
  });
}

/**
 * Send a fee-due reminder to a parent.
 *
 * Required AiSensy template (campaign: ark_fee_payment_reminder) — 3 variables:
 *   "Dear Parent, *{{1}}'s* fee of ₹{{2}} is due by {{3}}. Please contact us."
 */
export async function sendFeeReminder(params: {
  parentPhone:   string;
  parentName?:   string;
  studentName:   string;
  amountPending: number;
  dueDate:       string;
}): Promise<AisensyResult> {
  return sendWhatsApp({
    campaignName:   CAMPAIGNS.FEE_REMINDER,
    destination:    params.parentPhone,
    recipientName:  params.parentName || `Parent of ${params.studentName}`,
    templateParams: [
      params.studentName,
      params.amountPending.toLocaleString("en-IN"),
      params.dueDate,
    ],
  });
}

// ── Plain-text formatter (clipboard fallback when no phone on file) ─────────

export function formatMarksMessage(params: {
  studentName: string;
  marks:       number;
  totalMarks:  number;
  subject:     string;
  examType:    string;
  remarks:     string;
  teacherName: string;
  /**
   * The issuing institution. REQUIRED — this message is pasted into WhatsApp
   * and sent to a parent, and it used to be signed "ARK Learning Arena" for
   * every tenant. An optional parameter with a default is how that returns.
   */
  orgName:     string;
}): string {
  const pct = Math.round((params.marks / params.totalMarks) * 100);
  let grade = "Excellent";
  if (pct < 40)      grade = "Needs Improvement";
  else if (pct < 60) grade = "Below Average";
  else if (pct < 75) grade = "Average";
  else if (pct < 90) grade = "Good";

  const dateStr = new Date().toLocaleDateString("en-IN", {
    day: "numeric", month: "long", year: "numeric",
  });

  return [
    "----------------------------------",
    "   " + params.orgName.toUpperCase(),
    "   Student Performance Report",
    "----------------------------------",
    "",
    "Dear Parent,",
    "",
    `Student : ${params.studentName}`,
    `Subject : ${params.subject}`,
    `Exam    : ${params.examType}`,
    `Date    : ${dateStr}`,
    "",
    "----------------------------------",
    "  RESULT",
    "----------------------------------",
    `Marks   : ${params.marks} / ${params.totalMarks}`,
    `Percent : ${pct}%`,
    `Grade   : ${grade}`,
    "----------------------------------",
    "",
    "TEACHER'S REMARKS:",
    params.remarks || "No remarks.",
    "",
    `Teacher : ${params.teacherName}`,
    "",
    "----------------------------------",
    "Regards,",
    params.orgName,
    "----------------------------------",
  ].join("\n");
}
