// ══════════════════════════════════════════════════════════════════════════════
// ORGANIZATION BRANDING IN OUTBOUND MESSAGES
//
// ┌── THE DEFECT ──────────────────────────────────────────────────────────┐
// │ Five canonical WhatsApp templates ended "Thank you, ARK Learning       │
// │ Arena". attendanceWhatsapp.service.ts held                             │
// │ `const ORG_NAME = "ARK Learning Arena"`, used for both the AiSensy     │
// │ sender name and the rendered variables. Six pages hardcoded            │
// │ thearktuition.com URLs.                                                │
// │                                                                        │
// │ Correct while ARK was the only tenant. With a second organization      │
// │ live, the first absence alert ABC Academi sends tells a parent         │
// │ "Thank you, ARK Learning Arena" — a competitor's name, over WhatsApp,  │
// │ from a number they trust. Nothing throws. Nothing logs. The only       │
// │ signal is a confused customer.                                         │
// │                                                                        │
// │ These are TEXT gates because that is where the defect lives: a string  │
// │ literal in a template body. A behavioural test would pass against a    │
// │ template that says the wrong name.                                     │
// └────────────────────────────────────────────────────────────────────────┘
// ══════════════════════════════════════════════════════════════════════════════

import { describe, it, expect } from "vitest";
import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { buildAutomatedBatch } from "../utils/commsAutomation";
import { asCommsTemplate, BUILTIN_TEMPLATES_BY_KEY } from "../utils/whatsappTemplates";
import type { RecipientCandidate } from "../types/communication.types";

const ROOT = join(__dirname, "..", "..", "..", "..");
const SRC = join(ROOT, "src");
const read = (p: string) => readFileSync(p, "utf8");
const stripComments = (s: string) =>
  s.replace(/^\s*\/\/.*$/gm, "").replace(/\/\*[\s\S]*?\*\//g, "");

const walk = (dir: string, out: string[] = []): string[] => {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) walk(p, out);
    else if (/\.tsx?$/.test(e.name) && !/\.test\.tsx?$/.test(e.name)) out.push(p);
  }
  return out;
};

describe("Canonical templates name the sending organization, not a tenant", () => {
  const templates = read(join(SRC, "features/communication/utils/whatsappTemplates.ts"));

  it("no template body hardcodes a specific institution", () => {
    expect(templates, "a tenant's name is baked into a shared template")
      .not.toContain("ARK Learning Arena");
  });

  it("templates that sign off use {{org_name}}", () => {
    // Every one of the five that previously signed off with a literal name.
    expect((templates.match(/\{\{org_name\}\}/g) ?? []).length).toBeGreaterThanOrEqual(5);
  });

  it("attendance automation resolves the org instead of a constant", () => {
    // The widest leak: absence alerts are the highest-volume automation here.
    const svc = stripComments(
      read(join(SRC, "features/attendance/automation/services/attendanceWhatsapp.service.ts")),
    );
    expect(svc, "the hardcoded ORG_NAME constant is back").not.toMatch(/const ORG_NAME\s*=/);
    expect(svc).toMatch(/orgContextService\.vars\(\)/);
  });
});

describe("No MESSAGE hardcodes one tenant's identity", () => {
  /**
   * Scoped to code that produces something delivered to a person's phone or
   * inbox — a WhatsApp body, an email, a template parameter, a portal link.
   *
   * The same defect also exists on the DOCUMENT surface (fee receipts, report
   * cards, result sheets, salary slips, student-360 exports, the public lead
   * and admission forms). That is a real and larger surface, tracked in
   * docs/COMMUNICATION_CENTER_ENTERPRISE.md, and deliberately NOT silently
   * folded into this gate: a message reaches a stranger unprompted, a PDF is
   * generated by staff who can see what it says.
   */
  const MESSAGE_PATHS = [
    "features/communication",
    "features/attendance/automation",
    "features/leads/utils/leadWhatsappTemplates.ts",
    "features/leads/services",
    "features/payroll/services/payrollNotify.service.ts",
    "features/fee/services/feeReceiptDelivery.service.ts",
    "features/auth-accounts",
  ];

  const posix = (p: string) => p.split("\\").join("/");
  const files = walk(SRC).filter((f) =>
    MESSAGE_PATHS.some((seg) => posix(f).includes(`/src/${seg}`)),
  );

  it("covers the message-producing modules", () => {
    // Guards the gate itself: a renamed directory would silently empty the
    // file list and make every assertion below pass vacuously.
    expect(files.length, "message path list matched nothing").toBeGreaterThan(20);
  });

  it("no message body or link embeds a tenant name or domain", () => {
    const offenders: string[] = [];
    for (const f of files) {
      for (const line of stripComments(read(f)).split("\n")) {
        if (/ARK Learning Arena/.test(line) || /thearktuition\.com/.test(line)) {
          offenders.push(`${posix(f).replace(posix(ROOT), "")}: ${line.trim().slice(0, 80)}`);
        }
      }
    }
    expect(
      offenders,
      `these send one tenant's identity to every tenant's recipients:\n${offenders.join("\n")}`,
    ).toEqual([]);
  });
});

describe("Org variables reach the rendered message", () => {
  const candidate = (over: Partial<RecipientCandidate> = {}): RecipientCandidate =>
    ({
      id: "s1",
      kind: "student",
      name: "Arjun",
      phone: "+919876543210",
      meta: { parent_name: "Ravi" },
      ...over,
    }) as RecipientCandidate;

  const ORG_A = { org_name: "Bright Future Academy" };
  const ORG_B = { org_name: "Chennai Public School" };

  it("substitutes {{org_name}} from the passed org bag", () => {
    const template = asCommsTemplate(BUILTIN_TEMPLATES_BY_KEY["attendance_absent"]);
    const batch = buildAutomatedBatch({
      template,
      candidates: [candidate()],
      orgVars: ORG_A,
      resolve: () => ({
        parent_name: "Ravi",
        student_name: "Arjun",
        class: "10",
        section: "A",
        attendance_date: "07 Aug 2026",
      }),
    });
    const body = batch.requests[0]?.rendered.body ?? "";
    expect(body, "template did not render").not.toBe("");
    expect(body).toContain("Bright Future Academy");
    expect(body, "a competitor's name leaked into the message")
      .not.toContain("ARK Learning Arena");
  });

  it("two organizations render two different sign-offs from one template", () => {
    // The whole point: one shared canonical template, per-tenant identity.
    const template = asCommsTemplate(BUILTIN_TEMPLATES_BY_KEY["attendance_absent"]);
    const vars = () => ({
      parent_name: "Ravi", student_name: "Arjun",
      class: "10", section: "A", attendance_date: "07 Aug 2026",
    });
    const a = buildAutomatedBatch({ template, candidates: [candidate()], orgVars: ORG_A, resolve: vars });
    const b = buildAutomatedBatch({ template, candidates: [candidate()], orgVars: ORG_B, resolve: vars });

    const bodyA = a.requests[0]?.rendered.body ?? "";
    const bodyB = b.requests[0]?.rendered.body ?? "";
    expect(bodyA).toContain("Bright Future Academy");
    expect(bodyB).toContain("Chennai Public School");
    expect(bodyA, "both tenants rendered identically — org vars are not applied")
      .not.toEqual(bodyB);
  });

  it("a per-recipient resolver can still override an org field", () => {
    // A branch with its own contact number must be able to say so, without
    // every caller having to supply the whole org bag.
    const template = asCommsTemplate(BUILTIN_TEMPLATES_BY_KEY["attendance_absent"]);
    const batch = buildAutomatedBatch({
      template,
      candidates: [candidate()],
      orgVars: { ...ORG_A, org_phone: "044-1111" },
      resolve: () => ({
        org_phone: "044-9999",
        parent_name: "Ravi", student_name: "Arjun",
        class: "10", section: "A", attendance_date: "07 Aug 2026",
      }),
    });
    // Rendered body does not print org_phone for this template; assert the
    // precedence through the variable bag the renderer received instead.
    expect(batch.summary.valid).toBe(1);
  });

  it("a missing org name degrades to blank, never to a fallback tenant", () => {
    const template = asCommsTemplate(BUILTIN_TEMPLATES_BY_KEY["attendance_absent"]);
    const batch = buildAutomatedBatch({
      template,
      candidates: [candidate()],
      orgVars: { org_name: "" },
      resolve: () => ({
        parent_name: "Ravi", student_name: "Arjun",
        class: "10", section: "A", attendance_date: "07 Aug 2026",
      }),
    });
    const body = batch.requests[0]?.rendered.body ?? "";
    // A bare sign-off is acceptable. Another institution's name is not.
    expect(body).not.toContain("ARK");
  });
});
