// ─────────────────────────────────────────────────────────────────────────────
// Public API of the Exam feature module.
// External code imports from "@/features/exams" — never reach into subfolders.
//
// Phase 1: exam foundation + Manual Exam vertical — scheduling, marks entry,
//          centralised grading, ranking, analytics, audit, RBAC.
// Phase 2: MCQ Paper vertical — reusable question bank, paper builder (manual
//          + auto-generation), bulk import, version history, paper analytics.
//
// The `mode` field on Exam + the MCQ scoring layer reserve the model for the
// next phase (live MCQ Exam engine) — no rebuild required.
// ─────────────────────────────────────────────────────────────────────────────

// ── Types — Manual Exam ──────────────────────────────────────────────────────
export type {
  ExamMode,
  ExamType,
  ExamStatus,
  ResultsStatus,
  GradeBand,
  ExamAttachment,
  Exam,
  ExamResult,
  ScoredResult,
  ExamAuditEntry,
  ExamInput,
  RescheduleInput,
  MarksEntryRow,
  ExamStats,
  GradeDistributionItem,
  TopperRow,
  ExamAnalytics,
  ExamOverview,
} from "./types/exam.types";
export { EXAM_TYPES } from "./types/exam.types";

// ── Types — MCQ Paper ────────────────────────────────────────────────────────
export type {
  McqQuestionType,
  McqDifficulty,
  McqQuestionStatus,
  McqPaperStatus,
  McqGenerationMode,
  McqOption,
  NumericalAnswer,
  McqQuestion,
  McqQuestionInput,
  QuestionScope,
  QuestionBankFilters,
  GenerationRules,
  McqPaper,
  McqPaperInput,
  McqPaperQuestion,
  PaperQuestionView,
  PaperQuestionDraft,
  McqPaperVersion,
  McqAuditEntry,
  McqPaperOverview,
  ChapterDistItem,
  DifficultyDistItem,
  QuestionTypeDistItem,
  McqPaperAnalytics,
  BulkImportRow,
  BulkImportReport,
  McqResponse,
  ScoredAnswer,
  AttemptScore,
} from "./types/mcq.types";
export { MCQ_QUESTION_TYPES, MCQ_DIFFICULTIES } from "./types/mcq.types";

// ── Grading, MCQ scoring & access layers ─────────────────────────────────────
export {
  round2,
  DEFAULT_GRADE_SCHEME,
  schemeFor,
  percentageOf,
  gradeFor,
  isPass,
  scoreResult,
  assignRanks,
  computeStats,
  gradeDistribution,
  validateScheme,
  DIFFICULTY_WEIGHT,
  effectiveMarks,
  paperTotalMarks,
  estimateDifficultyScore,
  complexityLabel,
  estimatedAvgScorePct,
  chapterDistribution,
  difficultyDistribution,
  typeDistribution,
  paperInsights,
  correctOptionIds,
  answerKeyError,
  scoreAnswer,
  scoreAttempt,
  normalizeQuestionText,
  selectQuestionsForGeneration,
  canManagePaper,
  canManageQuestion,
  canShareGlobally,
  type ScoreInput,
  type ScoreOutput,
  type AccessUser,
} from "./utils";

// ── Schemas ──────────────────────────────────────────────────────────────────
export {
  examFormSchema,
  rescheduleSchema,
  type ExamFormValues,
  type RescheduleFormValues,
} from "./schemas/exam.schema";
export {
  questionFormSchema,
  paperFormSchema,
  generationRulesSchema,
  type QuestionFormValues,
  type PaperFormValues,
  type GenerationRulesValues,
} from "./schemas/mcq.schema";

// ── Services ─────────────────────────────────────────────────────────────────
export {
  examService,
  examResultsService,
  examAnalyticsService,
  examAuditService,
  examLookupsService,
  mcqQuestionService,
  mcqPaperService,
  mcqImportService,
  mcqAnalyticsService,
  mcqAuditService,
  type AuditActor,
  type LookupOption,
  type BatchOption,
  type StudentOption,
  type QuestionOwner,
} from "./services";

// ── Hooks ────────────────────────────────────────────────────────────────────
export {
  useExams,
  useExam,
  useExamResults,
  useExamLookups,
  useBatchRoster,
  useCreateExam,
  useUpdateExam,
  useRescheduleExam,
  useSetExamStatus,
  useDeleteExam,
  useSetResultsStatus,
  useSaveMarks,
  useExamAnalytics,
  useExamOverview,
  useExamAudit,
  useMcqQuestions,
  useMcqQuestion,
  useMcqChapters,
  useCreateQuestion,
  useUpdateQuestion,
  useDeleteQuestion,
  useSetQuestionStatus,
  useToggleFavorite,
  useCommitImport,
  useMcqPapers,
  useMcqPaper,
  useMcqPaperQuestions,
  useMcqPaperOverview,
  useMcqPaperVersions,
  useCreatePaper,
  useUpdatePaper,
  useDeletePaper,
  useSetPaperStatus,
  useClonePaper,
  useSavePaperQuestions,
  useMcqPaperAnalytics,
  useMcqPaperAudit,
} from "./hooks";

// ── Components ───────────────────────────────────────────────────────────────
export {
  ExamStatusChip,
  ResultsStatusChip,
  GradeBadge,
  MarksEntryDialog,
  ExamAnalyticsDialog,
  DifficultyBadge,
  QuestionTypeBadge,
  PaperStatusChip,
  QuestionStatusChip,
  QuestionEditorDialog,
  QuestionBankBrowser,
  QuestionPreviewDrawer,
  AutoGenerateDialog,
  BulkImportDialog,
  PaperAnalyticsDialog,
  PaperPreviewDialog,
  PaperVersionHistoryDialog,
} from "./components";

// ── Pages ────────────────────────────────────────────────────────────────────
export {
  CreateManualExamPage,
  ManageManualExamPage,
  CreateMcqPaperPage,
  ManageMcqPaperPage,
} from "./pages";
