import { useEffect, useMemo, useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useLocation, useNavigate, useParams } from "react-router-dom";
import {
  ArrowLeft,
  Eye,
  GripVertical,
  Loader2,
  Save,
  Sparkles,
  Trash2,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";
import { useAuth } from "@/contexts/AuthContext";
import { useCanDo } from "@/features/rbac";
import { paperFormSchema, type PaperFormValues } from "../schemas/mcq.schema";
import {
  canManagePaper,
  complexityLabel,
  effectiveMarks,
  estimateDifficultyScore,
  paperTotalMarks,
} from "../utils";
import {
  useExamLookups,
  useCreatePaper,
  useMcqPaper,
  useMcqPaperQuestions,
  useSavePaperQuestions,
  useUpdatePaper,
} from "../hooks";
import {
  AutoGenerateDialog,
  BulkImportDialog,
  DifficultyBadge,
  QuestionBankBrowser,
  QuestionEditorDialog,
  QuestionPreviewDrawer,
  QuestionTypeBadge,
} from "../components";
import type {
  GenerationRules,
  McqGenerationMode,
  McqPaperInput,
  McqQuestion,
} from "../types/mcq.types";

// ─────────────────────────────────────────────────────────────────────────────
// MCQ Paper builder — create / edit. The left column is the question bank
// browser; the right column is the paper canvas (meta form + drag-ordered
// question list + live totals). Saving creates/updates the paper, then writes
// the question set through the service, which recomputes totals + difficulty
// centrally. One page serves create and edit (an :id param switches mode).
// ─────────────────────────────────────────────────────────────────────────────

interface BuilderItem {
  question: McqQuestion;
  /** Per-paper marks override, kept as text ("" = use the bank marks). */
  marksOverride: string;
}

const resolveOverride = (text: string): number | null => {
  const t = text.trim();
  if (t === "") return null;
  const n = Number(t);
  return Number.isFinite(n) && n > 0 ? n : null;
};

const CreateMcqPaperPage = () => {
  const { id } = useParams<{ id?: string }>();
  const navigate = useNavigate();
  const { pathname } = useLocation();
  const { user } = useAuth();
  const { canDo } = useCanDo();

  const isEdit = !!id;
  const base = pathname.startsWith("/management") ? "/management" : "/admin";
  const managePath = `${base}/exams/mcq-papers`;

  const { data: lookups } = useExamLookups();
  const subjects = lookups?.subjects ?? [];
  const standards = lookups?.standards ?? [];

  const { data: existing } = useMcqPaper(id ?? null);
  const { data: existingQuestions } = useMcqPaperQuestions(id ?? null);

  const createMut = useCreatePaper();
  const updateMut = useUpdatePaper();
  const saveQuestionsMut = useSavePaperQuestions();

  const [items, setItems] = useState<BuilderItem[]>([]);
  const [genMode, setGenMode] = useState<McqGenerationMode>("manual");
  const [genRules, setGenRules] = useState<GenerationRules | null>(null);

  // Dialog state.
  const [editorOpen, setEditorOpen] = useState(false);
  const [editingQuestion, setEditingQuestion] = useState<McqQuestion | null>(
    null,
  );
  const [previewQuestion, setPreviewQuestion] = useState<McqQuestion | null>(
    null,
  );
  const [autoOpen, setAutoOpen] = useState(false);
  const [importOpen, setImportOpen] = useState(false);
  const [dragIndex, setDragIndex] = useState<number | null>(null);

  const form = useForm<PaperFormValues>({
    resolver: zodResolver(paperFormSchema),
    defaultValues: {
      title: "",
      description: "",
      instructions: "",
      durationMinutes: 60,
      negativeMarking: false,
      setCount: 1,
      randomize: false,
    },
  });

  // Prefill in edit mode once the paper + its questions arrive.
  useEffect(() => {
    if (!existing) return;
    form.reset({
      title: existing.title,
      subjectId: existing.subjectId,
      standardId: existing.standardId,
      description: existing.description ?? "",
      instructions: existing.instructions ?? "",
      durationMinutes: existing.durationMinutes,
      negativeMarking: existing.negativeMarking,
      setCount: existing.setCount,
      randomize: existing.randomize,
    });
    setGenMode(existing.generationMode);
    setGenRules(existing.generationRules ?? null);
  }, [existing, form]);

  useEffect(() => {
    if (!existingQuestions) return;
    setItems(
      existingQuestions.map((q) => ({
        question: q,
        marksOverride: q.marksOverride != null ? String(q.marksOverride) : "",
      })),
    );
  }, [existingQuestions]);

  const addedIds = useMemo(
    () => new Set(items.map((i) => i.question.id)),
    [items],
  );

  // Live totals — every figure from the centralised scoring layer.
  const scored = useMemo(
    () =>
      items.map((i) => ({
        difficulty: i.question.difficulty,
        effectiveMarks: effectiveMarks(
          i.question.marks,
          resolveOverride(i.marksOverride),
        ),
      })),
    [items],
  );
  const totalMarks = paperTotalMarks(scored);
  const difficultyScore = estimateDifficultyScore(scored);

  // ── Permission gate ─────────────────────────────────────────────────────────
  const permitted = isEdit
    ? canDo("exam.mcq.paper_edit") &&
      (!existing || canManagePaper(existing, user ?? {}))
    : canDo("exam.mcq.paper_create");

  // ── Builder ops ─────────────────────────────────────────────────────────────
  const addQuestion = (q: McqQuestion) => {
    if (addedIds.has(q.id)) return;
    setItems((prev) => [...prev, { question: q, marksOverride: "" }]);
  };
  const removeAt = (idx: number) =>
    setItems((prev) => prev.filter((_, i) => i !== idx));
  const patchOverride = (idx: number, value: string) =>
    setItems((prev) =>
      prev.map((it, i) => (i === idx ? { ...it, marksOverride: value } : it)),
    );

  // Native drag-reorder.
  const onDrop = (target: number) => {
    if (dragIndex === null || dragIndex === target) return;
    setItems((prev) => {
      const next = [...prev];
      const [moved] = next.splice(dragIndex, 1);
      next.splice(target, 0, moved);
      return next;
    });
    setDragIndex(null);
  };

  const onAutoGenerated = (questions: McqQuestion[], rules: GenerationRules) => {
    setItems(questions.map((q) => ({ question: q, marksOverride: "" })));
    setGenMode("auto");
    setGenRules(rules);
  };

  // ── Save ────────────────────────────────────────────────────────────────────
  const buildInput = (values: PaperFormValues): McqPaperInput => ({
    title: values.title,
    subjectId: values.subjectId ?? null,
    subjectName: subjects.find((s) => s.id === values.subjectId)?.name ?? null,
    standardId: values.standardId ?? null,
    standardName:
      standards.find((s) => s.id === values.standardId)?.name ?? null,
    description: values.description || null,
    instructions: values.instructions || null,
    durationMinutes: values.durationMinutes,
    negativeMarking: values.negativeMarking,
    setCount: values.setCount,
    randomize: values.randomize,
    generationMode: genMode,
    generationRules: genRules,
  });

  const save = form.handleSubmit(async (values) => {
    if (items.length === 0) {
      toast.error("Add at least one question to the paper");
      return;
    }
    const drafts = items.map((it, i) => ({
      questionId: it.question.id,
      sortOrder: i,
      marksOverride: resolveOverride(it.marksOverride),
    }));
    try {
      let paperId = id;
      if (isEdit && id) {
        await updateMut.mutateAsync({ id, input: buildInput(values) });
      } else {
        const created = await createMut.mutateAsync(buildInput(values));
        paperId = created.id;
      }
      if (paperId) {
        await saveQuestionsMut.mutateAsync({ paperId, drafts });
      }
      toast.success(isEdit ? "Paper updated" : "MCQ paper created");
      navigate(managePath);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Failed to save paper");
    }
  });

  const saving =
    createMut.isPending || updateMut.isPending || saveQuestionsMut.isPending;

  if (!permitted) {
    return (
      <div className="py-16 text-center text-sm text-muted-foreground">
        You do not have permission to {isEdit ? "edit" : "create"} MCQ papers.
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <header className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
        <div>
          <h1 className="text-xl md:text-2xl font-display font-semibold text-foreground">
            {isEdit ? "Edit MCQ Paper" : "Create MCQ Paper"}
          </h1>
          <p className="text-sm text-muted-foreground">
            Build a paper from the question bank — manually or auto-generated.
          </p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" size="sm" onClick={() => navigate(managePath)}>
            <ArrowLeft className="w-3.5 h-3.5 mr-1.5" /> Back
          </Button>
          <Button size="sm" onClick={save} disabled={saving}>
            {saving ? (
              <Loader2 className="w-3.5 h-3.5 mr-1.5 animate-spin" />
            ) : (
              <Save className="w-3.5 h-3.5 mr-1.5" />
            )}
            {isEdit ? "Save Paper" : "Create Paper"}
          </Button>
        </div>
      </header>

      <div className="grid grid-cols-1 lg:grid-cols-[360px_1fr] gap-4">
        {/* ── Question bank ───────────────────────────────────────────────── */}
        <aside className="rounded-lg border border-border/60 bg-card/40 p-3 h-[calc(100vh-220px)] min-h-[420px]">
          <QuestionBankBrowser
            subjects={subjects}
            addedIds={addedIds}
            onAdd={addQuestion}
            onPreview={(q) => setPreviewQuestion(q)}
            onEdit={(q) => {
              setEditingQuestion(q);
              setEditorOpen(true);
            }}
            onNew={() => {
              setEditingQuestion(null);
              setEditorOpen(true);
            }}
            onImport={() => setImportOpen(true)}
          />
        </aside>

        {/* ── Paper canvas ────────────────────────────────────────────────── */}
        <section className="space-y-4">
          {/* Paper meta */}
          <div className="rounded-lg border border-border/60 bg-card/60 p-4 space-y-3">
            <Field label="Paper Title *" error={form.formState.errors.title?.message}>
              <Input
                placeholder="e.g. Physics — Class 12 Mock Test 1"
                {...form.register("title")}
              />
            </Field>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <Field label="Subject">
                <select
                  {...form.register("subjectId")}
                  className="w-full bg-background border border-border rounded-md px-3 py-2 text-sm"
                >
                  <option value="">— Select —</option>
                  {subjects.map((s) => (
                    <option key={s.id} value={s.id}>
                      {s.name}
                    </option>
                  ))}
                </select>
              </Field>
              <Field label="Standard">
                <select
                  {...form.register("standardId")}
                  className="w-full bg-background border border-border rounded-md px-3 py-2 text-sm"
                >
                  <option value="">— Select —</option>
                  {standards.map((s) => (
                    <option key={s.id} value={s.id}>
                      {s.name}
                    </option>
                  ))}
                </select>
              </Field>
            </div>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
              <Field label="Duration (min)">
                <Input type="number" {...form.register("durationMinutes")} />
              </Field>
              <Field label="Paper Sets">
                <Input type="number" {...form.register("setCount")} />
              </Field>
              <Field label="Negative Marking">
                <label className="flex items-center gap-2 h-9 text-xs">
                  <input type="checkbox" {...form.register("negativeMarking")} />
                  Enabled
                </label>
              </Field>
              <Field label="Randomize">
                <label className="flex items-center gap-2 h-9 text-xs">
                  <input type="checkbox" {...form.register("randomize")} />
                  Shuffle
                </label>
              </Field>
            </div>
            <Field label="Instructions">
              <textarea
                rows={2}
                placeholder="Exam-day instructions for students…"
                {...form.register("instructions")}
                className="w-full bg-background border border-border rounded-md px-3 py-2 text-sm"
              />
            </Field>
          </div>

          {/* Live summary */}
          <div className="grid grid-cols-3 gap-3">
            <Summary label="Questions" value={`${items.length}`} />
            <Summary label="Total Marks" value={`${totalMarks}`} />
            <Summary
              label="Difficulty"
              value={`${difficultyScore} · ${complexityLabel(difficultyScore)}`}
            />
          </div>

          {/* Builder toolbar */}
          <div className="flex items-center justify-between">
            <p className="text-sm font-semibold text-foreground">
              Paper Questions
            </p>
            <Button
              size="sm"
              variant="outline"
              className="h-7 text-xs"
              onClick={() => setAutoOpen(true)}
            >
              <Sparkles className="w-3 h-3 mr-1" /> Auto-generate
            </Button>
          </div>

          {/* Question list — drag to reorder */}
          {items.length === 0 ? (
            <div className="rounded-lg border border-dashed border-border/70 py-12 text-center text-sm text-muted-foreground">
              No questions yet. Add from the bank or auto-generate.
            </div>
          ) : (
            <ol className="space-y-1.5">
              {items.map((it, idx) => {
                const ov = resolveOverride(it.marksOverride);
                return (
                  <li
                    key={it.question.id}
                    draggable
                    onDragStart={() => setDragIndex(idx)}
                    onDragOver={(e) => e.preventDefault()}
                    onDrop={() => onDrop(idx)}
                    className={`flex items-start gap-2 rounded-lg border bg-card/60 p-2.5 ${
                      dragIndex === idx
                        ? "border-accent"
                        : "border-border/60"
                    }`}
                  >
                    <span className="cursor-grab text-muted-foreground pt-0.5">
                      <GripVertical className="w-4 h-4" />
                    </span>
                    <span className="text-xs font-semibold text-muted-foreground w-5 pt-0.5">
                      {idx + 1}
                    </span>
                    <div className="flex-1 min-w-0">
                      <p className="text-xs text-foreground line-clamp-2">
                        {it.question.questionText}
                      </p>
                      <div className="flex flex-wrap items-center gap-1 mt-1">
                        <QuestionTypeBadge type={it.question.questionType} />
                        <DifficultyBadge
                          difficulty={it.question.difficulty}
                        />
                        <span className="text-[10px] text-muted-foreground">
                          {effectiveMarks(it.question.marks, ov)} marks
                          {it.question.chapter
                            ? ` · ${it.question.chapter}`
                            : ""}
                        </span>
                      </div>
                    </div>
                    <Input
                      value={it.marksOverride}
                      onChange={(e) => patchOverride(idx, e.target.value)}
                      placeholder={`${it.question.marks}`}
                      title="Marks override"
                      className="w-14 h-7 text-xs"
                    />
                    <button
                      type="button"
                      title="Preview"
                      onClick={() => setPreviewQuestion(it.question)}
                      className="text-muted-foreground hover:text-accent pt-0.5"
                    >
                      <Eye className="w-3.5 h-3.5" />
                    </button>
                    <button
                      type="button"
                      title="Remove"
                      onClick={() => removeAt(idx)}
                      className="text-muted-foreground hover:text-destructive pt-0.5"
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                    </button>
                  </li>
                );
              })}
            </ol>
          )}
        </section>
      </div>

      {/* ── Dialogs ─────────────────────────────────────────────────────────── */}
      <QuestionEditorDialog
        open={editorOpen}
        question={editingQuestion}
        subjects={subjects}
        onOpenChange={setEditorOpen}
        onCreated={(q) => addQuestion(q)}
      />
      <QuestionPreviewDrawer
        question={previewQuestion}
        onOpenChange={() => setPreviewQuestion(null)}
      />
      <AutoGenerateDialog
        open={autoOpen}
        subjects={subjects}
        onOpenChange={setAutoOpen}
        onGenerated={onAutoGenerated}
      />
      <BulkImportDialog open={importOpen} onOpenChange={setImportOpen} />
    </div>
  );
};

// ── Small primitives ─────────────────────────────────────────────────────────
const Field = ({
  label,
  error,
  children,
}: {
  label: string;
  error?: string;
  children: React.ReactNode;
}) => (
  <div className="space-y-1">
    <label className="text-xs font-medium text-foreground">{label}</label>
    {children}
    {error && <p className="text-[11px] text-destructive">{error}</p>}
  </div>
);

const Summary = ({ label, value }: { label: string; value: string }) => (
  <div className="rounded-lg border border-border/60 bg-card/60 p-3">
    <p className="text-[10px] uppercase tracking-wider text-muted-foreground">
      {label}
    </p>
    <p className="text-lg font-display font-semibold text-foreground mt-0.5">
      {value}
    </p>
  </div>
);

export default CreateMcqPaperPage;
