// ──────────────────────────────────────────────────────────────────────────────
// DOCUMENT BRANDING — TYPES
//
// Deliberately import-free. These types are shared by the resolver (which talks
// to Supabase), the theme builder (pure maths) and the document components
// (pure rendering), and a dependency here would drag Supabase into a unit test
// of a colour calculation.
// ──────────────────────────────────────────────────────────────────────────────

/**
 * Everything a printable document needs to identify the organization that
 * issued it.
 *
 * Every field is a plain string, never null or undefined. A document that
 * prints "undefined" where an address belongs is worse than one that prints
 * nothing, and `??` chains scattered through JSX are how that happens. The
 * resolver normalises once; the components render what they are given.
 *
 * `organizationName` is the ONE field that is never empty — a document with no
 * issuer is not a document. The resolver falls back through display_name →
 * app_name → legal_name → slug to guarantee it.
 */
export interface DocumentBranding {
  /** Public-facing name. Never empty. */
  organizationName: string;
  /** Registered entity name, when it differs. "" when unknown. */
  legalName: string;
  /** Absolute URL, same-origin path, or "" — "" renders a monogram. */
  logoUrl: string;
  address: string;
  phone: string;
  email: string;
  website: string;
  /** GST / tax registration. Rendered only when non-empty. */
  taxId: string;
  /** Printed under the signature rule. Falls back to organizationName. */
  authorizedSignatory: string;
  /** Replaces "Generated by Smart ARK" when the tenant sets one. */
  footerNote: string;
  /** Receipt colours. "" means "use the system default". */
  receiptPrimaryColor: string;
  receiptSecondaryColor: string;
  receiptAccentColor: string;
}

/**
 * A resolved, contrast-safe palette. Produced by `buildReceiptTheme` from a
 * `DocumentBranding`; consumed by the document components.
 *
 * The components read ONLY these fields — they never see a raw tenant colour.
 * That is what makes "a tenant cannot make its own receipt unreadable" a
 * structural property rather than a promise: the unreadable combination is not
 * reachable from the component's API.
 */
export interface ReceiptTheme {
  /** Header band and amount band base. The tenant's colour, verbatim. */
  primary: string;
  secondary: string;
  accent: string;

  /** `linear-gradient(...)` for the header band. */
  headerGradient: string;
  /** `linear-gradient(...)` for the amount band. */
  amountGradient: string;

  /** Readable text on the header band — near-black or white, whichever wins. */
  onPrimary: string;
  /** Same, at reduced emphasis, for the address lines under the name. */
  onPrimaryMuted: string;
  /** Border for the document-type pill, derived from `onPrimary`. */
  onPrimaryBorder: string;
  /** Fill for the document-type pill. */
  onPrimaryFill: string;

  /**
   * The primary colour DARKENED until it is readable on white.
   *
   * Section titles and their rules sit on the page, not on the band. A tenant
   * choosing a pale yellow gets a readable darkened variant here while the
   * header band still uses their actual choice.
   */
  primaryOnWhite: string;
  /** Same treatment for the accent, used on highlighted values. */
  accentOnWhite: string;

  /** Neutrals. Fixed — these are page furniture, not brand expression. */
  ink: string;
  muted: string;
  faint: string;
  line: string;
  danger: string;
}
