export type {
  AcademicYear,
  AcademicYearInput,
  Standard,
  StandardInput,
  Subject,
  SubjectInput,
  CourseType,
  CourseTypeInput,
  Tax,
  TaxInput,
  Batch,
  BatchInput,
  StandardCourseType,
  BatchSubject,
  DayOfWeek,
  TimetablePeriod,
  TimetablePeriodUpsert,
} from "./setup.types";
