import { useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Loader2, Sparkles } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";
import {
  generationRulesSchema,
  type GenerationRulesValues,
} from "../schemas/mcq.schema";
import { selectQuestionsForGeneration } from "../utils";
import { mcqQuestionService } from "../services";
import { useMcqChapters } from "../hooks";
import type { GenerationRules, McqQuestion } from "../types/mcq.types";
import type { LookupOption } from "../services";

interface Props {
  open: boolean;
  subjects: LookupOption[];
  onOpenChange: (open: boolean) => void;
  onGenerated: (questions: McqQuestion[], rules: GenerationRules) => void;
}

// ─────────────────────────────────────────────────────────────────────────────
// Automatic paper generation — pick a balanced set from the bank by difficulty
// mix and (optional) chapter weightage. The selection itself runs in the pure
// `selectQuestionsForGeneration` scoring helper; this dialog only gathers the
// rules and the candidate pool.
// ─────────────────────────────────────────────────────────────────────────────
export const AutoGenerateDialog = ({
  open,
  subjects,
  onOpenChange,
  onGenerated,
}: Props) => {
  const [busy, setBusy] = useState(false);
  const [weights, setWeights] = useState<Record<string, string>>({});
  // Blueprint balancing — on by default. A generated paper should spread across
  // cognitive levels and formats unless a teacher deliberately turns that off.
  const [balanceBloom, setBalanceBloom] = useState(true);
  const [balanceTypes, setBalanceTypes] = useState(true);

  const form = useForm<GenerationRulesValues>({
    resolver: zodResolver(generationRulesSchema),
    defaultValues: {
      totalQuestions: 20,
      easyPct: 30,
      mediumPct: 50,
      hardPct: 20,
      marksPerQuestion: 1,
    },
  });

  const subjectId = form.watch("subjectId");
  const { data: chapters = [] } = useMcqChapters(subjectId || undefined);

  useEffect(() => {
    if (open) {
      form.reset();
      setWeights({});
      setBalanceBloom(true);
      setBalanceTypes(true);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open]);

  const submit = form.handleSubmit(async (values) => {
    setBusy(true);
    try {
      const chapterWeightage = chapters
        .map((chapter) => ({
          chapter,
          weight: Number(weights[chapter] || 0),
        }))
        .filter((w) => w.weight > 0);

      const rules: GenerationRules = {
        totalQuestions: values.totalQuestions,
        difficultyMix: {
          easy: values.easyPct,
          medium: values.mediumPct,
          hard: values.hardPct,
        },
        chapterWeightage,
        marksPerQuestion: values.marksPerQuestion,
        subjectId: values.subjectId ?? null,
        balanceBloom,
        balanceTypes,
      };

      const pool = await mcqQuestionService.list({
        subjectId: values.subjectId || undefined,
      });
      if (pool.length === 0) {
        toast.error("No bank questions match — add questions first.");
        return;
      }

      const { selected, shortfall } = selectQuestionsForGeneration(pool, rules);
      if (selected.length === 0) {
        toast.error("Could not select any questions for these rules.");
        return;
      }
      if (shortfall > 0) {
        toast.warning(
          `Only ${selected.length} of ${values.totalQuestions} could be filled — the bank is short.`,
        );
      } else {
        toast.success(`Generated a ${selected.length}-question paper`);
      }
      onGenerated(selected, rules);
      onOpenChange(false);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Generation failed");
    } finally {
      setBusy(false);
    }
  });

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-lg max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Sparkles className="w-4 h-4 text-accent" /> Auto-generate Paper
          </DialogTitle>
        </DialogHeader>

        <form onSubmit={submit} className="space-y-4">
          <div className="grid grid-cols-2 gap-3">
            <Field
              label="Total Questions *"
              error={form.formState.errors.totalQuestions?.message}
            >
              <Input type="number" {...form.register("totalQuestions")} />
            </Field>
            <Field label="Marks / question">
              <Input
                type="number"
                step="0.5"
                {...form.register("marksPerQuestion")}
              />
            </Field>
          </div>

          <Field label="Subject">
            <select
              {...form.register("subjectId")}
              className="w-full bg-background border border-border rounded-md px-3 py-2 text-sm"
            >
              <option value="">All subjects</option>
              {subjects.map((s) => (
                <option key={s.id} value={s.id}>
                  {s.name}
                </option>
              ))}
            </select>
          </Field>

          {/* Difficulty mix */}
          <div>
            <p className="text-xs font-medium text-foreground mb-1.5">
              Difficulty mix (must total 100%)
            </p>
            <div className="grid grid-cols-3 gap-3">
              <Field label="Easy %">
                <Input type="number" {...form.register("easyPct")} />
              </Field>
              <Field
                label="Medium %"
                error={form.formState.errors.mediumPct?.message}
              >
                <Input type="number" {...form.register("mediumPct")} />
              </Field>
              <Field label="Hard %">
                <Input type="number" {...form.register("hardPct")} />
              </Field>
            </div>
          </div>

          {/* Blueprint balancing */}
          <div className="rounded-lg border border-border/60 bg-muted/20 p-3 space-y-2">
            <p className="text-xs font-medium text-foreground">Blueprint balance</p>
            <label className="flex items-start gap-2 cursor-pointer">
              <input
                type="checkbox"
                checked={balanceBloom}
                onChange={(e) => setBalanceBloom(e.target.checked)}
                className="mt-0.5"
              />
              <span className="text-xs text-muted-foreground">
                <span className="text-foreground font-medium">Balance Bloom taxonomy</span> — spread
                questions across Remember → Create instead of clumping on recall.
              </span>
            </label>
            <label className="flex items-start gap-2 cursor-pointer">
              <input
                type="checkbox"
                checked={balanceTypes}
                onChange={(e) => setBalanceTypes(e.target.checked)}
                className="mt-0.5"
              />
              <span className="text-xs text-muted-foreground">
                <span className="text-foreground font-medium">Mix question types</span> — alternate
                MCQ / short / long rather than grouping by format.
              </span>
            </label>
            <p className="text-[10px] text-muted-foreground pt-0.5">
              Balancing re-orders within each difficulty band — your easy/medium/hard split is
              always honoured exactly.
            </p>
          </div>

          {/* Chapter weightage */}
          {chapters.length > 0 && (
            <div className="rounded-lg border border-border/60 bg-muted/20 p-3">
              <p className="text-xs font-medium text-foreground mb-2">
                Chapter weightage (optional — leave 0 to ignore)
              </p>
              <div className="space-y-1.5 max-h-40 overflow-y-auto">
                {chapters.map((c) => (
                  <div key={c} className="flex items-center gap-2">
                    <span className="text-xs flex-1 truncate">{c}</span>
                    <Input
                      type="number"
                      value={weights[c] ?? ""}
                      onChange={(e) =>
                        setWeights((w) => ({ ...w, [c]: e.target.value }))
                      }
                      placeholder="0"
                      className="w-20 h-7 text-xs"
                    />
                    <span className="text-[10px] text-muted-foreground">%</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          <div className="flex gap-2">
            <Button type="submit" disabled={busy}>
              {busy ? (
                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
              ) : (
                <Sparkles className="w-4 h-4 mr-2" />
              )}
              Generate
            </Button>
            <Button
              type="button"
              variant="ghost"
              onClick={() => onOpenChange(false)}
            >
              Cancel
            </Button>
          </div>
          <p className="text-[11px] text-muted-foreground">
            Generated questions replace the current builder list — you can still
            edit, reorder or remove them before saving.
          </p>
        </form>
      </DialogContent>
    </Dialog>
  );
};

const Field = ({
  label,
  error,
  children,
}: {
  label: string;
  error?: string;
  children: React.ReactNode;
}) => (
  <div className="space-y-1">
    <label className="text-xs font-medium text-foreground">{label}</label>
    {children}
    {error && <p className="text-[11px] text-destructive">{error}</p>}
  </div>
);
