// ── Parent Portal — Reports ──────────────────────────────────────────────────
// Every report here is generated by an EXISTING engine:
//   360° / Progress → generateStudent360 (features/students)
//   Attendance      → the portal's own print view over student_attendance
//   Fee statement   → print view over the same ledger the Fees tab shows
// No parallel report generator, no new PDF dependency.

import { useState } from "react";
import { FileBarChart, FileSpreadsheet, FileText, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { generateStudent360 } from "@/features/students/services";
import { closeReportWindow, openReportWindow, renderReportWindow } from "@/lib/reportWindow";
import { useAuth } from "@/contexts/AuthContext";
import { useActiveChild } from "../providers/ActiveChildProvider";
import { useChildAttendance, useChildInsights } from "../hooks/useChildData";
import { parentPortalService } from "../services/parentPortal.service";
import { parentAuditService } from "../services/parentAudit.service";
import { Card, PageHeader, SectionTitle, formatDate, inr } from "../components/primitives";
import type { Student } from "@/features/students/types";

const esc = (s: unknown) =>
  String(s ?? "").replace(/[&<>"']/g, (c) =>
    c === "&" ? "&amp;" : c === "<" ? "&lt;" : c === ">" ? "&gt;" : c === '"' ? "&quot;" : "&#39;",
  );

const shell = (title: string, student: Student, body: string) => `<!doctype html><html><head>
<meta charset="utf-8"><title>${esc(title)} — ${esc(student.name)}</title><style>
  body{font-family:ui-sans-serif,system-ui,Segoe UI,sans-serif;color:#0f172a;margin:0}
  .page{max-width:794px;margin:0 auto;padding:40px 34px}
  .brand{font-weight:800;letter-spacing:.12em;color:#4f46e5;font-size:13px}
  h1{font-size:21px;margin:5px 0 4px}
  .sub{color:#64748b;font-size:12px;margin:0 0 18px}
  table{width:100%;border-collapse:collapse;font-size:12px;margin:8px 0}
  th{background:#f1f5f9;text-align:left;padding:6px 8px;border-bottom:1px solid #e2e8f0;font-weight:600}
  td{padding:6px 8px;border-bottom:1px solid #f1f5f9}
  .r{text-align:right}
  .foot{margin-top:26px;font-size:10px;color:#94a3b8;text-align:center;border-top:1px solid #e2e8f0;padding-top:10px}
  @media print{@page{size:A4;margin:15mm}}
</style></head><body><div class="page">
  <div class="brand">ARK LEARNING ARENA</div>
  <h1>${esc(title)}</h1>
  <p class="sub">${esc(student.name)} · ${esc([student.standardName, student.section, student.batch].filter(Boolean).join(" · "))} · Generated ${formatDate(new Date().toISOString())}</p>
  ${body}
  <p class="foot">ARK Learning Arena · Parent Portal · Confidential</p>
</div>
<script>window.addEventListener('load',function(){setTimeout(function(){window.print()},300)})</script>
</body></html>`;

export const ParentReportsPage = () => {
  const { parent } = useAuth();
  const { activeChild } = useActiveChild();
  const student = activeChild?.student;
  const { data: days = [] } = useChildAttendance(student?.id);
  const { data: insights } = useChildInsights(student?.id);
  const [busy, setBusy] = useState<string | null>(null);

  const audit = (detail: string) => {
    if (!parent || !student) return;
    void parentAuditService.log({
      parentAccountId: parent.accountId,
      studentId: student.id,
      event: "download_report",
      detail,
    });
  };

  const run360 = async (format: "pdf" | "xlsx") => {
    if (!student || busy) return;
    // Excel writes a file directly and needs no window; PDF must open one
    // synchronously inside the click.
    const win = format === "pdf" ? openReportWindow() : null;
    if (format === "pdf" && !win) return;
    setBusy(format);
    try {
      await generateStudent360(student, format, win);
      audit(`student_360_${format}`);
    } catch (e) {
      closeReportWindow(win);
      toast.error(`Could not generate the report: ${(e as Error).message}`);
    } finally {
      setBusy(null);
    }
  };

  const runAttendance = () => {
    if (!student) return;
    const monthly = parentPortalService.monthlyAttendance(days);
    if (monthly.length === 0) {
      toast.error("No attendance has been recorded yet.");
      return;
    }
    const win = openReportWindow();
    if (!win) return;
    const rows = monthly
      .map(
        (m) =>
          `<tr><td>${esc(m.month)}</td><td class="r">${m.present}</td><td class="r">${m.late}</td><td class="r">${m.absent}</td><td class="r">${m.total}</td><td class="r">${m.percent}%</td></tr>`,
      )
      .join("");
    renderReportWindow(
      shell(
        "Attendance Report",
        student,
        `<table><thead><tr><th>Month</th><th class="r">Present</th><th class="r">Late</th><th class="r">Absent</th><th class="r">Total</th><th class="r">%</th></tr></thead><tbody>${rows}</tbody></table>`,
      ),
      win,
    );
    audit("attendance_report");
  };

  const runFee = () => {
    if (!student) return;
    const fee = insights?.fee;
    if (!fee) {
      toast.error("No fee record has been assigned yet.");
      return;
    }
    const win = openReportWindow();
    if (!win) return;
    const receipts = fee.receipts
      .map(
        (r) =>
          `<tr><td>${esc(r.receiptNo ?? "—")}</td><td>${formatDate(r.date)}</td><td>${esc(r.method)}</td><td class="r">${esc(inr(r.amount))}</td></tr>`,
      )
      .join("");
    renderReportWindow(
      shell(
        "Fee Statement",
        student,
        `<table><tbody>
          <tr><td>Total fee</td><td class="r">${esc(inr(fee.total))}</td></tr>
          <tr><td>Discount</td><td class="r">${esc(inr(fee.discount))}</td></tr>
          <tr><td>Collected</td><td class="r">${esc(inr(fee.received))}</td></tr>
          <tr><td><b>Balance</b></td><td class="r"><b>${esc(inr(fee.pending))}</b></td></tr>
        </tbody></table>
        <h3 style="font-size:13px;margin:18px 0 4px">Payment history</h3>
        ${receipts ? `<table><thead><tr><th>Receipt</th><th>Date</th><th>Method</th><th class="r">Amount</th></tr></thead><tbody>${receipts}</tbody></table>` : "<p style='font-size:12px;color:#64748b'>No payments recorded.</p>"}`,
      ),
      win,
    );
    audit("fee_statement");
  };

  if (!activeChild || !student) return null;

  const REPORTS = [
    {
      id: "360",
      title: "Student 360° report",
      desc: "The full 12-section dossier: profile, academics, attendance, fees, receipts, communication, timeline, documents and recommendations.",
      icon: FileBarChart,
      run: () => run360("pdf"),
    },
    {
      id: "xlsx",
      title: "Student 360° (Excel)",
      desc: "The same dossier as a multi-sheet workbook.",
      icon: FileSpreadsheet,
      run: () => run360("xlsx"),
    },
    {
      id: "attendance",
      title: "Attendance report",
      desc: "Month-by-month present / late / absent totals with percentages.",
      icon: FileText,
      run: runAttendance,
    },
    {
      id: "fee",
      title: "Fee statement",
      desc: "Total, discount, collected and balance, with the full payment history.",
      icon: FileText,
      run: runFee,
    },
  ];

  return (
    <div className="max-w-3xl mx-auto">
      <PageHeader title="Reports" subtitle={student.name} />

      <SectionTitle>Available downloads</SectionTitle>
      <div className="space-y-2.5">
        {REPORTS.map((r) => {
          const Icon = r.icon;
          return (
            <Card key={r.id} className="!p-4">
              <div className="flex items-start justify-between gap-3">
                <div className="flex items-start gap-3 min-w-0">
                  <span className="rounded-lg bg-accent/10 p-2 shrink-0">
                    <Icon className="w-4 h-4 text-accent" />
                  </span>
                  <div className="min-w-0">
                    <p className="text-sm font-semibold text-foreground">{r.title}</p>
                    <p className="text-xs text-muted-foreground mt-0.5">{r.desc}</p>
                  </div>
                </div>
                <button
                  onClick={r.run}
                  disabled={busy !== null}
                  className="shrink-0 inline-flex items-center gap-1.5 rounded-lg border border-border px-3 py-1.5 text-[11px] font-medium text-muted-foreground hover:text-accent hover:border-accent/40 transition-colors disabled:opacity-40"
                >
                  {busy === r.id ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : null}
                  Generate
                </button>
              </div>
            </Card>
          );
        })}
      </div>

      <Card className="mt-4">
        <p className="text-xs text-muted-foreground">
          Individual fee receipts and certificates are downloaded from the Fees and Documents pages.
          Every download is recorded in your account's activity log.
        </p>
      </Card>
    </div>
  );
};

export default ParentReportsPage;
