#!/usr/bin/env node
// ═══════════════════════════════════════════════════════════════════════════
// SELF-HOST THE WEBFONTS
//
//   node scripts/fetch-fonts.mjs           refresh public/fonts/ + fonts.css
//   node scripts/fetch-fonts.mjs --check   verify what is on disk, download nothing
//
// The app used `@import url(https://fonts.googleapis.com/...)` at the top of
// src/index.css. Phase 0's CSP is `style-src 'self' 'unsafe-inline'` and
// `font-src 'self' data:`, so that stylesheet AND the .woff2 files it points at
// were both blocked — every surface silently fell back to a system sans.
//
// We self-host rather than widen the CSP. Rationale in
// docs/PRODUCTION_DEPLOYMENT.md §18 and at the top of src/styles/fonts.css.
//
// This is a script rather than a one-off manual download because the alternative
// rots: fonts get a new version (v20 → v21), somebody re-copies one @font-face
// by hand, and the unicode-range drifts from the file it points at. Then a
// Vietnamese or Cyrillic name renders as tofu on one page and not another.
// ═══════════════════════════════════════════════════════════════════════════

import { writeFileSync, mkdirSync, existsSync, readdirSync, statSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const FONT_DIR = join(ROOT, "public", "fonts");
const CSS_OUT = join(ROOT, "src", "styles", "fonts.css");

// Keep in sync with tailwind.config.ts fontFamily: sans → Inter, display → Space Grotesk.
const GOOGLE_CSS =
  "https://fonts.googleapis.com/css2" +
  "?family=Inter:wght@300..800" +
  "&family=Space+Grotesk:wght@300..700" +
  "&display=swap";

// Google serves woff2 + variable fonts only to browsers it recognises. With the
// default fetch UA it returns legacy ttf and one file PER WEIGHT.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";

const CHECK = process.argv.includes("--check");

/** Parse Google's CSS into one descriptor per @font-face. */
function parseFaces(css) {
  // Each @font-face is preceded by a `/* subset */` comment.
  const subsets = css
    .split("\n")
    .map((l) => /^\/\* ([a-z-]+) \*\/$/.exec(l.trim())?.[1])
    .filter(Boolean);

  return css.split("@font-face").slice(1).map((b, i) => {
    const family = /font-family:\s*'([^']+)'/.exec(b)[1];
    const weight = /font-weight:\s*([^;]+);/.exec(b)[1].trim();
    const url = /url\((https:[^)]+)\)/.exec(b)[1];
    const range = /unicode-range:\s*([^;]+);/.exec(b)[1].trim();
    const version = /\/(v\d+)\//.exec(url)[1];
    const subset = subsets[i];
    const slug = family.toLowerCase().replace(/\s+/g, "-");
    // The version is in the FILENAME on purpose: public/ files are served
    // verbatim with no content hash, and vercel.json caches /fonts/ for a year
    // as immutable. A new version must therefore be a new URL, or browsers keep
    // the old file until the cache expires.
    return { family, weight, url, range, version, subset, file: `${slug}-${subset}-${version}.woff2` };
  });
}

function renderCss(faces) {
  const header = `/* ────────────────────────────────────────────────────────────────────────────
   SELF-HOSTED WEBFONTS — Inter (body) + Space Grotesk (headings)
   ────────────────────────────────────────────────────────────────────────────
   Generated by scripts/fetch-fonts.mjs. Do not hand-edit; re-run the script.

   These replace an \`@import url(https://fonts.googleapis.com/css2?...)\` that
   Phase 0's Content-Security-Policy blocked outright: style-src is
   'self' 'unsafe-inline', so the stylesheet never loaded, and font-src is
   'self' data:, so the .woff2 files would have been blocked too.

   Self-hosting was chosen over widening the CSP because it is strictly safer
   AND strictly faster — see docs/PRODUCTION_DEPLOYMENT.md §18. In short:
     • no third-party origin gains the right to serve CSS into this document
     • no extra DNS + TLS handshakes to two more hosts on first paint
     • an @import inside CSS is render-blocking and serialised AFTER the
       stylesheet parses, so it was among the last things to start loading
     • visitor IPs stop being disclosed to a third party (DPDP / GDPR)
     • the Capacitor Android build works offline; a remote font does not

   These are VARIABLE fonts: one file per subset covers the whole weight
   range, which is why font-weight below is a range rather than a number.
   unicode-range is preserved exactly as Google serves it, so browsers still
   download only the subsets a page actually needs — a Latin-only page pulls
   ~70 KB of the ~266 KB total.
   ──────────────────────────────────────────────────────────────────────── */
`;
  return (
    header +
    faces
      .map(
        (f) => `
/* ${f.family} — ${f.subset} */
@font-face {
  font-family: '${f.family}';
  font-style: normal;
  font-weight: ${f.weight};
  font-display: swap;
  src: url('/fonts/${f.file}') format('woff2');
  unicode-range: ${f.range};
}`,
      )
      .join("\n") + "\n"
  );
}

const css = await (await fetch(GOOGLE_CSS, { headers: { "User-Agent": UA } })).text();
if (!css.includes("@font-face")) {
  console.error("Google returned no @font-face blocks. Refusing to overwrite.");
  process.exit(1);
}
const faces = parseFaces(css);

if (CHECK) {
  const onDisk = existsSync(FONT_DIR) ? readdirSync(FONT_DIR) : [];
  const missing = faces.filter((f) => !onDisk.includes(f.file));
  const extra = onDisk.filter((f) => f.endsWith(".woff2") && !faces.some((x) => x.file === f));
  console.log(`upstream faces: ${faces.length}   on disk: ${onDisk.length}`);
  if (missing.length) console.log("MISSING:\n  " + missing.map((f) => f.file).join("\n  "));
  if (extra.length) console.log("STALE:\n  " + extra.join("\n  "));
  if (!missing.length && !extra.length) console.log("public/fonts/ matches upstream.");
  process.exit(missing.length ? 1 : 0);
}

mkdirSync(FONT_DIR, { recursive: true });
let bytes = 0;
for (const f of faces) {
  const res = await fetch(f.url, { headers: { "User-Agent": UA } });
  if (!res.ok) { console.error(`FAILED ${f.file}: HTTP ${res.status}`); process.exit(1); }
  const buf = Buffer.from(await res.arrayBuffer());
  // Guard against silently writing an error page as a font.
  if (buf.subarray(0, 4).toString("latin1") !== "wOF2") {
    console.error(`FAILED ${f.file}: not a woff2 file`);
    process.exit(1);
  }
  writeFileSync(join(FONT_DIR, f.file), buf);
  bytes += buf.length;
  console.log(`${String(buf.length).padStart(7)} B  ${f.file}`);
}

mkdirSync(dirname(CSS_OUT), { recursive: true });
writeFileSync(CSS_OUT, renderCss(faces));
console.log(`\n${faces.length} files, ${(bytes / 1024).toFixed(0)} KB total → public/fonts/`);
console.log(`wrote ${CSS_OUT.replace(ROOT, ".")}`);
